config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :companies
  resources :tweets, only: [:index]

  namespace :api do
    resources :users
    resources :tweets
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Company < ApplicationRecord
  has_many :users
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, length: { maximum: 180 }
  validates_uniqueness_of :body, scope: :user, conditions: -> { where(created_at: DateTime.now-24.hours..) }

  scope :unaffiliated, -> { joins(:user).where(user: { company_id: nil })}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  company_id             :integer
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
# Foreign Keys
#
#  company_id  (company_id => companies.id)
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company, optional: true
  scope :by_company, -> (identifier) { where(company: identifier) if identifier.present? }
  scope :by_username, -> (username) { where('username LIKE ?', username) if username.present? }
end

app/controllers/api/tweets_controller.rb
module Api
  class TweetsController < ApplicationController
    skip_before_action :verify_authenticity_token

    TWEETS_PER_PAGE = 50

    def create
      return head :bad_request if params[:body].blank? || params[:user_id].blank?

      @tweet = Tweet.create!(
          user_id: params[:user_id],
          body: params[:body]
        )

      render json: @tweet
    end

    def index
      @tweets = Tweet.all
      @tweets = @tweets.unaffiliated if params[:affiliated].present? && params[:affiliated] == false

      render json: @tweets.order("created_at ASC").limit(TWEETS_PER_PAGE).offset(offset)
    end

    private

    def page_params
      params.permit(:page).merge(per_page: TWEETS_PER_PAGE)
    end

    def page
      params[:page]
    end

    def offset
      return 0 if !page || page == 1

      page * (page.to_i - 1)
    end
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def index
      users = User
                .by_company(params[:company_id])
                .by_username(search_params[:username])
      render json: users.all
    end

    private

    def search_params
      params.permit(:company_id)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tweets = Tweet.preload(user: :company).distinct(:user_id).order("created_at DESC").limit(20)
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-2">
    <h1>Welcome to Beon Twitter</h1>
    <p> See what’s happening in the world right now</p>
    <% unless user_signed_in? %>
      <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-primary" %>
      <%= link_to 'Sign in', new_user_session_path, class: "btn btn-secondary" %>
    <% end %>
  </div>

  <div class="col-md-10 mt-5">
    <div class="tweets">
      <% @tweets.each do |tweet| %>
        <div class="card my-2">
          <div class="card-header">
            <div class="col-md-6">
              Author:
              <%= tweet.user.username %>

              <% if tweet.user.company %>
                | Organization: <%= tweet.user.company.name %>
              <% end %>
            </div>
            <div class="col-md-6">
              <small><%= time_ago_in_words(tweet.created_at) %></small>
            </div>
          </div>
          <div class="card-body">
            <%= tweet.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <%= link_to "Help", '#' %>
  <%= link_to "About", '#'  %>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light border-bottom">
  <div class="container-fluid">
    <%= link_to "Beon Twitter", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <% if user_signed_in? %>
          <%# TODO: handle active class %>
          <li class="nav-item">
            <%= link_to '#{users_path}', class: 'nav-link', aria: { current: 'page' } do %>
              <span>My Company</span>
            <% end %>
          </li>
          <li>
            <%= link_to '#', class: 'nav-link' do %>
              <span>Profile</span>
            <% end %>
          </li>
          <li>
            <%= link_to '#', class: 'nav-link' do %>
              <span>My Tweets</span>
            <% end %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path, class: 'nav-link' do %>
              <span>Sign in</span>
            <% end %>
          </li>
        <% end %>
      </ul>
      <div id="search-bar-js"></div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTwitterInterview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <main class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </main>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>